version: '3'
services:
  frontend:
    image: rush
    container_name: frontend.digiu.local
    ports:
      - '3000:3000'
    working_dir: /app
    entrypoint: bash -c "cd packages/pancake-swap-interface && rushx start"
    volumes:
      - ../../:/app
        - ../../.rush:/root/.rush

  uikit:
    image: rush
    container_name: uikit.digiu.local
    ports:
      - '6006:6006'
    working_dir: /app
    entrypoint: bash -c "cd packages/pancake-uikit && rushx storybook"
    volumes:
      - ../../:/app
      - ../../.rush:/root/.rush

